package by.javatr.finances.controller;

/**
 * @author Aleh Yemelyanchyk on 12/28/2019.
 */
public enum CommandName {
    SIGN_IN_COMMAND,
    REMOVE_USER_COMMAND,
    LOG_IN_COMMAND,
    LOG_OUT_COMMAND,
    ADD_MONEY_ACCOUNT_COMMAND,
    REMOVE_MONEY_ACCOUNT_COMMAND,
    SHOW_BALANCE_COMMAND,
    ADD_INCOME_COMMAND,
    ADD_EXPENSE_COMMAND,
    DEPOSIT_MONEY_COMMAND,
    WITHDRAWAL_MONEY_COMMAND,
    GET_ACCOUNTS_COMMAND,
    WRONG_REQUEST_COMMAND,
    BACK_COMMAND,
    QUIT
}
